# Site settings
title: Emogirl
email: emogirl00272@gmail.com
description: My homepage.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://emogirl00272.github.io" # the base hostname & protocol for your site

# Identity
your-name: Konkin Ratmir
your-title: DC Engineer

# Social settings
email: emogirl00272@gmail.com
qr_url: 
500px_url:
facebook_url: https://facebook.com
github_url:
instagram_url: https://instagram.com/emogirl00272

# Build settings
markdown: kramdown
